define( function(){
    'use strict';

    var codes = {
            'backspace' : 8,
            'tab' : 9,
            'enter' : 13,
            'shift' : 16,
            'ctrl' : 17,
            'alt' : 18,
            'option' : 18,
            'pause' : 19,
            'caps' : 20,
            'esc' : 27,
            'escape' : 27,
            'pgUp' : 33,
            'pageUp' : 33,
            'pgDown' : 34,
            'pageDown' : 34,
            'end' : 35,
            'home' : 36,
            'left' : 37,
            'up' : 38,
            'right' : 39,
            'down' : 40,
            'ins' : 45,
            'insert' : 45,
            'del' : 46,
            'delete' : 46,
            '0' : 48,
            '1' : 49,
            '2' : 50,
            '3' : 51,
            '4' : 52,
            '5' : 53,
            '6' : 54,
            '7' : 55,
            '8' : 56,
            '9' : 57,
            'a' : 65,
            'b' : 66,
            'c' : 67,
            'd' : 68,
            'e' : 69,
            'f' : 70,
            'g' : 71,
            'h' : 72,
            'i' : 73,
            'j' : 74,
            'k' : 75,
            'l' : 76,
            'm' : 77,
            'n' : 78,
            'o' : 79,
            'p' : 80,
            'q' : 81,
            'r' : 82,
            's' : 83,
            't' : 84,
            'u' : 85,
            'v' : 86,
            'w' : 87,
            'x' : 88,
            'y' : 89,
            'z' : 90,
            '⌘' : 91,
            'cmd' : 91,
            'leftWindow' : 91,
            'rightWindow' :  92,
            '⌘2' : 93,
            'cmd2' : 93,
            'select' : 93,
            'numpad0' : 96,
            'numpad1' : 97,
            'numpad2' : 98,
            'numpad3' : 99,
            'numpad4' : 100,
            'numpad5' : 101,
            'numpad6' : 102,
            'numpad7' : 103,
            'numpad8' : 104,
            'numpad9' : 105,
            'multiply' : 106,
            'add' : 107,
            'subtract' : 109,
            'decimal' : 110,
            'divide' : 111,
            'f1' : 112,
            'f2' : 113,
            'f3' : 114,
            'f4' : 115,
            'f5' : 116,
            'f6' : 117,
            'f7' : 118,
            'f8' : 119,
            'f9' : 120,
            'f10' : 121,
            'f11' : 122,
            'f12' : 123,
            'numLock' : 144,
            'scrollLock' : 145,
            ';' : 186,
            ':' : 186,
            'semi-colon' : 186,
            '=' : 187,
            '+' : 187,
            'equal' : 187,
            ',' : 188,
            '<' : 188,
            'comma' : 188,
            '-' : 189,
            '_' : 189,
            'dash' : 189,
            '.' : 190,
            '>' : 190,
            'period' : 190,
            '/' : 191,
            'fwdSlash' : 191,
            'forwardSlash' : 191,
            '`' : 192,
            '~' : 192,
            'grave' : 192,
            '[' : 219,
            '{' : 219,
            'openBracket' : 219,
            '\\' : 220,
            '|' : 220,
            'bkSlash' : 220,
            'backSlash' : 220,
            ']' : 221,
            '}' : 221,
            'closeBraket' : 221,
            '"' : 222,
            'singleQuote' : 222
        },
        keyNums,

        rev = function( obj ){
            if ( ! keyNums ){
                keyNums = {};
                for ( var key in codes ){
                    if ( codes.hasOwnProperty( key ) ){
                        keyNums[ codes[ key ] ] = key;
                    }
                }
            }

            return keyNums;
        };

        return function( name ){

                if ( typeof name === 'number' ) {
                    return rev( codes )[ name ];
                }

                return codes[ name ];
            };
});
